# DATA INVENTORY ASSESSMENT

In [2]:
import pandas as pd
#loading dataset
df = pd.read_csv("C:\\Users\\kusha\\OneDrive\\Desktop\\DA\\My projects\\Marketing Campaign Analysis\\raw dataset\\global_ads_performance_dataset.csv")

#Table overview
#returning dimension of dataframe
print("Rows:", df.shape[0])  
print("Columns:", df.shape[1]) 
df.head()

Rows: 1800
Columns: 14

,date,platform,campaign_type,industry,country,impressions,clicks,CTR,CPC,ad_spend,conversions,CPA,revenue,ROAS
0,2024-01-21,Google Ads,Search,Fintech,UAE,59886,2113,0.0353,1.26,2662.38,159,16.74,4803.43,1.80
1,2024-01-22,TikTok Ads,Search,EdTech,UK,135608,5220,0.0385,1.18,6159.60,411,14.99,64126.68,10.41
2,2024-06-15,TikTok Ads,Video,Healthcare,USA,92313,5991,0.0649,0.85,5092.35,267,19.07,10489.07,2.06
3,2024-01-02,TikTok Ads,Shopping,SaaS,Germany,83953,5935,0.0707,1.32,7834.20,296,26.47,50505.07,6.45
4,2024-02-22,TikTok Ads,Search,Healthcare,UK,91807,4489,0.0489,1.93,8663.77,107,80.97,3369.53,0.39

In [3]:
#Column Information 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1800 non-null   object
 1   platform       1800 non-null   object
 2   campaign_type  1800 non-null   object
 3   industry       1800 non-null   object
 4   country        1800 non-null   object
 5   impressions    1800 non-null   int64
 6   clicks         1800 non-null   int64
 7   CTR            1800 non-null   float64
 8   CPC            1800 non-null   float64
 9   ad_spend       1800 non-null   float64
 10  conversions    1800 non-null   int64
 11  CPA            1800 non-null   float64
 12  revenue        1800 non-null   float64
 13  ROAS           1800 non-null   float64
dtypes: float64(6), int64(3), object(5)
memory usage: 197.0+ KB

In [4]:
#Checkig unique values in categorical columns
categorical_columns = [

    'platform', 
    'campaign_type', 
    'industry', 
    'country'
]

for col in categorical_columns: 
    print(f"\n{col}:")
    print(df[col].unique())

platform:
['Google Ads' 'TikTok Ads' 'Meta Ads']

campaign_type:
['Search' 'Video' 'Shopping' 'Display']

industry:
['Fintech' 'EdTech' 'Healthcare' 'SaaS' 'E-commerce']

country:
['UAE' 'UK' 'USA' 'Germany' 'Canada' 'India' 'Australia']

In [5]:
#Statistical overview of numeric columns 
df.describe()

,impressions,clicks,CTR,CPC,ad_spend,conversions,CPA,revenue,ROAS
count,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000,1800.000000
mean,102919.018889,3962.675556,0.038427,1.572756,6171.527272,181.562222,46.608961,30101.850450,6.450367
std,55740.900690,2941.858037,0.017082,0.800872,5776.996958,171.424239,41.185556,34560.032941,6.590986
min,5059.000000,91.000000,0.008900,0.280000,58.000000,2.000000,4.800000,142.690000,0.130000
25%,54948.000000,1678.000000,0.025400,0.950000,1966.587500,59.000000,20.202500,7275.757500,2.170000
50%,103653.000000,3318.000000,0.035550,1.460000,4393.860000,130.000000,33.375000,18362.965000,4.295000
75%,150470.250000,5628.000000,0.049800,2.050000,8455.830000,252.250000,56.812500,38963.385000,8.212500
max,199650.000000,16660.000000,0.095600,3.950000,38453.320000,1151.000000,335.860000,295028.260000,49.000000

In [6]:
#Checking date raneg and number of unique dates 
print("Minimum date:", df['date'].min())
print("Maximum date:", df['date'].max())
print("Unique date:", df['date'].nunique())

Minimum date: 2024-01-01
Maximum date: 2024-12-30
Unique date: 360

In [8]:
# Checking number of records per date
df['date'].value_counts().describe()

count    360.000000
mean       5.000000
std        2.232952
min        1.000000
25%        3.000000
50%        5.000000
75%        7.000000
max       13.000000
Name: count, dtype: float64

In [9]:
#checking for completely duplicate rows
print("duplicate rows:", df.duplicated().sum())

duplicate rows: 0

In [10]:
#checking whether date + platform + campaign type + industry +country uniquely identifies each record
key_columns = [
    'date',
    'platform',
    'campaign_type',
    'industry',
    'country'
]

print("Duplicate combinations:", df.duplicated(subset=key_columns).sum())

Duplicate combinations: 12

In [11]:
#inspecting duplicate combinations
duplicates = df[df.duplicated(
    subset = key_columns, 
    keep = False
)].sort_values(key_columns)

duplicates

,date,platform,campaign_type,industry,country,impressions,clicks,CTR,CPC,ad_spend,conversions,CPA,revenue,ROAS
192,2024-01-04,Meta Ads,Shopping,EdTech,UK,117217,2133,0.0182,1.29,2751.57,129,21.33,25455.36,9.25
760,2024-01-04,Meta Ads,Shopping,EdTech,UK,184729,2586,0.0140,0.90,2327.40,201,11.58,16864.93,7.25
170,2024-02-20,Google Ads,Shopping,Fintech,UK,162489,4500,0.0277,3.03,13635.00,184,74.10,54944.54,4.03
1742,2024-02-20,Google Ads,Shopping,Fintech,UK,89431,3300,0.0369,1.47,4851.00,56,86.62,9891.88,2.04
365,2024-02-27,TikTok Ads,Search,SaaS,UAE,7637,415,0.0544,1.54,639.10,10,63.91,1137.83,1.78
578,2024-02-27,TikTok Ads,Search,SaaS,UAE,195972,13796,0.0704,0.50,6898.00,645,10.69,54701.33,7.93
842,2024-04-04,TikTok Ads,Search,SaaS,UK,45382,2246,0.0495,1.59,3571.14,46,77.63,2662.90,0.75
863,2024-04-04,TikTok Ads,Search,SaaS,UK,199291,16660,0.0836,1.16,19325.60,1016,19.02,207611.26,10.74
14,2024-04-22,TikTok Ads,Shopping,EdTech,Canada,37711,2111,0.0560,0.68,1435.48,92,15.60,13898.86,9.68
1495,2024-04-22,TikTok Ads,Shopping,EdTech,Canada,186006,9002,0.0484,1.52,13683.04,266,51.44,31194.26,2.28
375,2024-06-20,Meta Ads,Video,EdTech,Germany,29502,604,0.0205,1.61,972.44,30,32.41,5842.59,6.01
1787,2024-06-20,Meta Ads,Video,EdTech,Germany,95987,1919,0.0200,1.71,3281.49,124,26.46,28533.79,8.70
263,2024-06-23,Google Ads,Search,EdTech,UK,11305,562,0.0498,1.72,966.64,42,23.02,8107.06,8.39
1317,2024-06-23,Google Ads,Search,EdTech,UK,158778,7256,0.0457,1.50,10884.00,431,25.25,17905.23,1.65
805,2024-08-31,Meta Ads,Video,E-commerce,UAE,196373,5184,0.0264,0.86,4458.24,173,25.77,36583.06,8.21
812,2024-08-31,Meta Ads,Video,E-commerce,UAE,60919,1851,0.0304,1.79,3313.29,131,25.29,19210.72,5.80
120,2024-09-10,Google Ads,Video,Healthcare,Canada,65545,3355,0.0512,1.77,5938.35,196,30.30,57936.29,9.76
1508,2024-09-10,Google Ads,Video,Healthcare,Canada,111071,2865,0.0258,2.83,8107.95,39,207.90,8971.28,1.11
367,2024-09-11,Google Ads,Search,EdTech,UAE,32675,941,0.0288,1.09,1025.69,47,21.82,12632.32,12.32
1540,2024-09-11,Google Ads,Search,EdTech,UAE,100381,5691,0.0567,0.83,4723.53,321,14.72,58283.85,12.34
844,2024-12-05,TikTok Ads,Search,EdTech,India,71470,2065,0.0289,1.18,2436.70,37,65.86,10377.15,4.26
1041,2024-12-05,TikTok Ads,Search,EdTech,India,170529,11766,0.0690,1.48,17413.68,695,25.06,102403.13,5.88
548,2024-12-12,Google Ads,Shopping,SaaS,Canada,88251,2665,0.0302,1.29,3437.85,151,22.77,17509.21,5.09
1018,2024-12-12,Google Ads,Shopping,SaaS,Canada,162064,5607,0.0346,2.42,13568.94,77,176.22,8174.03,0.60

In [12]:
# Checking frequency of repeated dimension combinations

df.groupby(key_columns).size().value_counts().sort_index()

1    1776
2      12
Name: count, dtype: int64

In [13]:
# Checking uniqueness without date

non_date_key = [
    'platform',
    'campaign_type',
    'industry',
    'country'
]

print(
    "Duplicate combinations:",
    df.duplicated(subset=non_date_key).sum()
)

Duplicate combinations: 1393

In [14]:
# Checking whether adding ad_spend makes the combination unique
extended_key = [
    'date',
    'platform',
    'campaign_type',
    'industry',
    'country',
    'ad_spend'
]

print(
    "Duplicate combinations:",
    df.duplicated(subset=extended_key).sum()
)

Duplicate combinations: 0

In [15]:
# Comparing ad spend within repeated date-dimension combinations

duplicates.groupby(key_columns)['ad_spend'].nunique()

date        platform    campaign_type  industry    country
2024-01-04  Meta Ads    Shopping       EdTech      UK         2
2024-02-20  Google Ads  Shopping       Fintech     UK         2
2024-02-27  TikTok Ads  Search         SaaS        UAE        2
2024-04-04  TikTok Ads  Search         SaaS        UK         2
2024-04-22  TikTok Ads  Shopping       EdTech      Canada     2
2024-06-20  Meta Ads    Video          EdTech      Germany    2
2024-06-23  Google Ads  Search         EdTech      UK         2
2024-08-31  Meta Ads    Video          E-commerce  UAE        2
2024-09-10  Google Ads  Video          Healthcare  Canada     2
2024-09-11  Google Ads  Search         EdTech      UAE        2
2024-12-05  TikTok Ads  Search         EdTech      India      2
2024-12-12  Google Ads  Shopping       SaaS        Canada     2
Name: ad_spend, dtype: int64

In [16]:
# Check dataset dimensions and column names

print("Number of tables: 1")
print("Columns:")
for col in df.columns:
    print("-", col)

Number of tables: 1
Columns:
- date
- platform
- campaign_type
- industry
- country
- impressions
- clicks
- CTR
- CPC
- ad_spend
- conversions
- CPA
- revenue
- ROAS